### ISSUE TITLE
ConvertTo-PublishingServiceWdp.ps1 fails if $Destination parameter value has a trailing slash

### ISSUE THREAD

**Issue by sidm1983** [coreyasmith/Sitecore-Publishing-Service-Azure-Templates#1]
Hi Corey,

Thanks for these awesome scripts/templates. They have been a tremendous help.

While I was using `ConvertTo-PublishingServiceWdp.ps1` script, I passed in a destination path with a trailing slash and received an error. I realised the error was happening because of string concatenation with the $destinationPath variable that was resulting in a double slash in the final path for some of the files the script is creating on-the-fly. I forked this repo and applied a fix to allow for values with and without trailing slashes. Please review and merge in if you like. Pull request: #2

**Comment by sidm1983** [comment]
Pull request: #2

**Comment by coreyasmith** [comment]
Fixed in #2. Thanks @sidm1983! 🙌
